### ISSUE TITLE
[enhancement] : 사용자 자격증명시 예외 처리가 빠진 부분 

### ISSUE THREAD

**Issue by handyejee** [helloworld-bedev/study-together#11]
지난 PR에서 수정하기로 했던 사용자 로그인시 200만 주고 있는 부분의 수정 요청

[src/main/java/helloworld/studytogether/jwt/filter/LoginFilter.java]
`    response.setStatus(HttpStatus.OK.value());
  }
`

사용자가 잘못된 자격 증명을 입력했거나, 예기치 않은 에러가 발생했을 때 예외를 처리하는 기능을 넣으면 좋을 것 같습니다. 예외가 발생할 경우 401 Unauthorized 상태 코드를 반환하고, 로그를 남기는 것은 어떨까요? 현재 생각나는 방법으로는 catch와 HashMap을 쓰는 방법 정도가 있는데 더 좋은 방법이 있는지는 좀 더 고민해야 할 것 같아요.

**Comment by heekuukuu** [comment]
완료
