### ISSUE TITLE
fix : 로그인한 사용자가 로그인 api 재호출 시 오류가 발생하는 현상

### ISSUE THREAD

**Issue by handyejee** [helloworld-bedev/study-together#17]
- 재현절차
1. 회원가입한 사용자의 계정으로 로그인한다.
2. 로그인 한 사용자의 계정으로 로그인 api를 재호출한다 (/login)
3. Duplicate entry '3' for key 'refresh_token 에러메세지 확인

```
{
    "error": "Failed to generate tokens: could not execute statement [Duplicate entry '3' for key 'refresh_token.UKf95ixxe7pa48ryn1awmh2evt7'] [insert into refresh_token (expiration,refresh,user_id) values (?,?,?)]; SQL [insert into refresh_token (expiration,refresh,user_id) values (?,?,?)]; constraint [refresh_token.UKf95ixxe7pa48ryn1awmh2evt7]"
}
```

- 제안: login한 사용자가 로그인 한 api 재호출시 access token만 재발급 되는지, refreshtoken 까지 함께 재발급이 되는지 로직확인 필요
- 만약에 로그아웃 한 다음에 로그인을 다시 시도해야 하는경우라면 로그인 한 사용자가 api 재호출 했을때 예외 메세지 노출 처리가 필요해 보인다는 의견입니다.

**Comment by heekuukuu** [comment]
![무제 18](https://github.com/user-attachments/assets/d814f760-1747-42ef-a828-ae06b3e435e0)

**Comment by heekuukuu** [comment]
![무제 4](https://github.com/user-attachments/assets/610037e2-36c0-4fa8-b282-0bced5228f18)
