### ISSUE TITLE
enhancement : print 하고 있는 부분 로그로 변환 

### ISSUE THREAD

**Issue by handyejee** [helloworld-bedev/study-together#18]
- 지난 PR때 요청 드렸던 콘솔에 출력하고 있는 형태가 print, write 등 으로 현재 출력되고 있어 `@log4j` 사용해 로그로 변환하는 부분 수정 요청드립니다
- 기능에는 이상이 없으나 일관적이지 않게 로그가 출력되고 있어 프로젝트 전체의 통일성을 위해 제안드립니다!

**Comment by heekuukuu** [comment]
해결
